### ISSUE TITLE
No module is defined for 'package something'

### ISSUE THREAD

**Issue by itchyny** [eagletmt/unite-haddock#4]
`Unite hoogle` does not support opening the page of 'package something'.
For example, start `Unite hoogle` and filter by 'array', you see `package array` but selecting it throws an error `No module is defined for 'package array'`.

**Comment by eagletmt** [comment]
Currently it's expected behavior.

unite-haddock is intended to open haddock.
The main use case is to see documentation for the module, function or type you are using now, not to search for new ones.

To fix this issue, I'm willing to remove `package something` entries from candidates.
What do you think?

**Comment by itchyny** [comment]
OK. Agreed with excluding the entries.

**Comment by itchyny** [comment]
Thank you.
